export enum InvestmentStatus {
  PENDING_FUNDING = 'PENDING_FUNDING',
  ACTIVE = 'ACTIVE',
  MATURED_PENDING_PAYOUT = 'MATURED_PENDING_PAYOUT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
