export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  INVESTMENT_FUND = 'INVESTMENT_FUND',
  INVESTMENT_PAYOUT = 'INVESTMENT_PAYOUT',
  FEE = 'FEE',
  ADJUSTMENT = 'ADJUSTMENT',
}
