export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  INVESTMENT_FUND = 'INVESTMENT_FUND',
  INVESTMENT_PAYOUT = 'INVESTMENT_PAYOUT',
  FEE = 'FEE',
  ADJUSTMENT = 'ADJUSTMENT',
}
